---
- name: Ping Server
  hosts: prod
  gather_facts: true
  vars:
     a: 12
     b: 14
  tasks:
    - name: Ping 1
      ping:
      when: c == 12
      register: ping1_result
      ignore_errors: True

    - name: Ping 2
      ping:
      when: ping1_result is succeeded